projectPath=C\:\\Users\\Dell\\OneDrive\\Documents\\Desktop\\Arjun\\KatalonStudio_EventHub\\EventHub\\EventHub.prj
retry=0
testSuitePath=Test Suites/AllTC
browserType=Web Service
executionProfile=Demo
apiKey=2b50c712-3d3f-4eb8-8188-73ef9b0597a8
proxy.auth.option=NO_PROXY
proxy.system.option=NO_PROXY
proxy.system.applyToDesiredCapabilities=true
webui.autoUpdateDrivers=true
ai.provider=katalon_ai
config=
